apiVersion: apps/v1
kind: Deployment
metadata:
  name: fttx-customer-web
  namespace: devops-fttx-ns
  labels:
    app: fttx-customer-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fttx-customer-web
  template:
    metadata:
      labels:
        app: fttx-customer-web
    spec:
      containers:
        - name: fttx-customer-web
          image: registry.smart.com.kh/devops/fttx/customer:0.0.13
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "250Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1500m"
          env:
            - name: APP_ENV
              value: production
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: http
      imagePullSecrets:
        - name: fttx-image-pull-bot
