apiVersion: v1
kind: Service
metadata:
  name: fttx-customer-web
  namespace: devop-laravel-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: fttx-customer-web
